import "../index.css"

export default function AboutMe() {
    return <>
    <h1 className="about">About Pokedex</h1>
    <div className="about">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Neque egestas congue quisque egestas diam. Sed turpis tincidunt id aliquet. Placerat duis ultricies lacus sed turpis tincidunt id. Auctor augue mauris augue neque gravida in fermentum et sollicitudin. Massa massa ultricies mi quis. Turpis egestas pretium aenean pharetra. Quis auctor elit sed vulputate. Vel fringilla est ullamcorper eget nulla facilisi etiam. Sem fringilla ut morbi tincidunt augue. Eget nullam non nisi est sit amet. Pulvinar mattis nunc sed blandit. Massa vitae tortor condimentum lacinia quis vel. A iaculis at erat pellentesque adipiscing commodo. Et malesuada fames ac turpis egestas maecenas. Pretium vulputate sapien nec sagittis.</div>
    <div className="about">Commodo elit at imperdiet dui. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Viverra adipiscing at in tellus integer feugiat scelerisque varius. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Ultrices in iaculis nunc sed augue lacus viverra. Faucibus pulvinar elementum integer enim neque volutpat ac. Vitae justo eget magna fermentum iaculis eu. Integer quis auctor elit sed vulputate mi sit amet. Erat velit scelerisque in dictum non. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. In massa tempor nec feugiat. Eu augue ut lectus arcu bibendum at varius. Varius quam quisque id diam vel quam elementum.</div>
    <div className="about">Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Amet consectetur adipiscing elit ut. Sit amet nisl suscipit adipiscing bibendum est ultricies integer quis. Sit amet luctus venenatis lectus magna fringilla urna. Ut etiam sit amet nisl purus in mollis. Elementum tempus egestas sed sed risus. Ipsum dolor sit amet consectetur. Id interdum velit laoreet id donec. Adipiscing elit duis tristique sollicitudin nibh. Lectus mauris ultrices eros in cursus turpis massa. Adipiscing diam donec adipiscing tristique risus. Auctor augue mauris augue neque gravida in fermentum. Facilisi cras fermentum odio eu feugiat pretium. Aliquet lectus proin nibh nisl condimentum id venenatis. Amet risus nullam eget felis. Tincidunt ornare massa eget egestas purus viverra accumsan in. Sed faucibus turpis in eu mi bibendum. Orci a scelerisque purus semper eget duis at tellus. Nibh nisl condimentum id venenatis a condimentum. Viverra aliquet eget sit amet tellus cras adipiscing.</div>
    </>
}